// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $api_get from "./routes/api/get.tsx";
import * as $api_post from "./routes/api/post.tsx";
import * as $buscarpokemon from "./routes/buscarpokemon.tsx";
import * as $crearPokemon from "./routes/crearPokemon.tsx";
import * as $delete_name_ from "./routes/delete/[name].tsx";
import * as $get_name_ from "./routes/get/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $pokemon_name_ from "./routes/pokemon/[name].tsx";
import * as $AddForm from "./islands/AddForm.tsx";
import * as $Botonbuscar from "./islands/Botonbuscar.tsx";
import * as $Botoncasa from "./islands/Botoncasa.tsx";
import * as $BotoncrearP from "./islands/BotoncrearP.tsx";
import * as $BuscarPokemones from "./islands/BuscarPokemones.tsx";
import * as $ListaPokemones from "./islands/ListaPokemones.tsx";
import * as $Pokemon from "./islands/Pokemon.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/api/get.tsx": $api_get,
    "./routes/api/post.tsx": $api_post,
    "./routes/buscarpokemon.tsx": $buscarpokemon,
    "./routes/crearPokemon.tsx": $crearPokemon,
    "./routes/delete/[name].tsx": $delete_name_,
    "./routes/get/[name].tsx": $get_name_,
    "./routes/index.tsx": $index,
    "./routes/pokemon/[name].tsx": $pokemon_name_,
  },
  islands: {
    "./islands/AddForm.tsx": $AddForm,
    "./islands/Botonbuscar.tsx": $Botonbuscar,
    "./islands/Botoncasa.tsx": $Botoncasa,
    "./islands/BotoncrearP.tsx": $BotoncrearP,
    "./islands/BuscarPokemones.tsx": $BuscarPokemones,
    "./islands/ListaPokemones.tsx": $ListaPokemones,
    "./islands/Pokemon.tsx": $Pokemon,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
